version: '3.7'

services:
  db:
      image: postgres
      container_name: "postgres_test_app"
      command: -p 54320
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_NAME}
      ports:
        - "${DATABASE_PORT}:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
  django_app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    container_name: 'django_app'
#    command: bash -c "python3 manage.py runserver 0.0.0.0:5000"
    command: bash -c "python3 manage.py import_data '2020-1 UNLOCODE CodeListPart1.csv' && python3 manage.py runserver 0.0.0.0:5000"
    volumes:
      - .:/app
    ports:
      - '5000:5000'
    depends_on:
      - db
volumes:
  postgres_data:
  django_app:
